### ISSUE TITLE
Terraform outputs are not exposed as InSpec attributes anymore?

### ISSUE THREAD

**Issue by encron** [newcontext-oss/kitchen-terraform#272] opened 2018-09-14 15:35 UTC
Hey,

Since updating `kitchen-terraform` to `4.0.0` it seems my terraform outputs are not exposed as InSpec attributes anymore and I get the following error message:

```
  82   │ E, [2018-09-14T17:17:12.403949 #27170] ERROR -- Kitchen: ---Nested Exception---
  83   │ E, [2018-09-14T17:17:12.403970 #27170] ERROR -- Kitchen: Class: Kitchen::ActionFailed
  84   │ E, [2018-09-14T17:17:12.403991 #27170] ERROR -- Kitchen: Message: Failed to complete #verify action: [Profile 'tests from {:path=>".foo.bar.ins
       │ pec-tests"}' does not have a attribute with name 'internal_dns_names']
  85   │ E, [2018-09-14T17:17:12.404012 #27170] ERROR -- Kitchen: ----------------------
  86   │ E, [2018-09-14T17:17:12.404038 #27170] ERROR -- Kitchen: ------Backtrace-------
  87   │ E, [2018-09-14T17:17:12.404061 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/inspec-2.2.101/lib/inspec/attribute_registry.rb:54:in `find_attribute'
  88   │ E, [2018-09-14T17:17:12.404102 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/inspec-2.2.101/lib/inspec/attribute_registry.rb:19:in `find_attribute'
  89   │ E, [2018-09-14T17:17:12.404125 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/inspec-2.2.101/lib/inspec/control_eval_context.rb:147:in `block (2 levels) in create'
  90   │ E, [2018-09-14T17:17:12.404147 #27170] ERROR -- Kitchen: /foo/bar/test/integration/inspec-tests/controls/foobar.rb:3:in `load_with_context'
  91   │ E, [2018-09-14T17:17:12.404169 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/inspec-2.2.101/lib/inspec/profile_context.rb:160:in `instance_eval'
  92   │ E, [2018-09-14T17:17:12.404190 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/inspec-2.2.101/lib/inspec/profile_context.rb:160:in `load_with_context'
  93   │ E, [2018-09-14T17:17:12.404211 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/inspec-2.2.101/lib/inspec/profile_context.rb:144:in `load_control_file'
  94   │ E, [2018-09-14T17:17:12.404233 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/inspec-2.2.101/lib/inspec/profile.rb:185:in `block in collect_tests'
  95   │ E, [2018-09-14T17:17:12.404255 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/inspec-2.2.101/lib/inspec/profile.rb:182:in `each'
  96   │ E, [2018-09-14T17:17:12.404277 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/inspec-2.2.101/lib/inspec/profile.rb:182:in `collect_tests'
  97   │ E, [2018-09-14T17:17:12.404298 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/inspec-2.2.101/lib/inspec/runner.rb:92:in `block in load'
  98   │ E, [2018-09-14T17:17:12.404347 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/inspec-2.2.101/lib/inspec/runner.rb:81:in `each'
  99   │ E, [2018-09-14T17:17:12.404371 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/inspec-2.2.101/lib/inspec/runner.rb:81:in `load'
 100   │ E, [2018-09-14T17:17:12.404393 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/inspec-2.2.101/lib/inspec/runner.rb:102:in `run'
 101   │ E, [2018-09-14T17:17:12.404414 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.0.0/lib/kitchen/terraform/inspec.rb:45:in `exec'
 102   │ E, [2018-09-14T17:17:12.404436 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.0.0/lib/kitchen/terraform/inspec_with_hosts.rb:33:in `block in exec'
 103   │ E, [2018-09-14T17:17:12.404457 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.0.0/lib/kitchen/terraform/system.rb:50:in `block in each_host'
 104   │ E, [2018-09-14T17:17:12.404479 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.0.0/lib/kitchen/terraform/system.rb:49:in `each'
 105   │ E, [2018-09-14T17:17:12.404501 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.0.0/lib/kitchen/terraform/system.rb:49:in `each_host'
 106   │ E, [2018-09-14T17:17:12.404523 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.0.0/lib/kitchen/terraform/inspec_with_hosts.rb:30:in `exec'
 107   │ E, [2018-09-14T17:17:12.404545 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.0.0/lib/kitchen/terraform/system.rb:101:in `verify'
 108   │ E, [2018-09-14T17:17:12.404567 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.0.0/lib/kitchen/verifier/terraform.rb:192:in `verify'
 109   │ E, [2018-09-14T17:17:12.404588 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.0.0/lib/kitchen/verifier/terraform.rb:83:in `block in call'
 110   │ E, [2018-09-14T17:17:12.404610 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.0.0/lib/kitchen/verifier/terraform.rb:82:in `each'
 111   │ E, [2018-09-14T17:17:12.404632 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/kitchen-terraform-4.0.0/lib/kitchen/verifier/terraform.rb:82:in `call'
 112   │ E, [2018-09-14T17:17:12.404654 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:458:in `block in verify_action'
 113   │ E, [2018-09-14T17:17:12.404693 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:551:in `synchronize_or_call'
 114   │ E, [2018-09-14T17:17:12.404717 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:513:in `block in action'
 115   │ E, [2018-09-14T17:17:12.404739 #27170] ERROR -- Kitchen: /usr/local/Cellar/ruby/2.5.1/lib/ruby/2.5.0/benchmark.rb:293:in `measure'
 116   │ E, [2018-09-14T17:17:12.404760 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:512:in `action'
 117   │ E, [2018-09-14T17:17:12.404782 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:450:in `verify_action'
 118   │ E, [2018-09-14T17:17:12.404803 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:382:in `block (2 levels) in transition_to'
 119   │ E, [2018-09-14T17:17:12.404825 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/lifecycle_hooks.rb:45:in `run_with_hooks'
 120   │ E, [2018-09-14T17:17:12.404888 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:381:in `block in transition_to'
 121   │ E, [2018-09-14T17:17:12.404919 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `each'
 122   │ E, [2018-09-14T17:17:12.404938 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:380:in `transition_to'
 123   │ E, [2018-09-14T17:17:12.404958 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/instance.rb:162:in `verify'
 124   │ E, [2018-09-14T17:17:12.404977 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `public_send'
 125   │ E, [2018-09-14T17:17:12.404996 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:197:in `run_action_in_thread'
 126   │ E, [2018-09-14T17:17:12.405016 #27170] ERROR -- Kitchen: /usr/local/lib/ruby/gems/2.5.0/gems/test-kitchen-1.23.2/lib/kitchen/command.rb:169:in `block (2 levels) in run_action'
 127   │ E, [2018-09-14T17:17:12.405035 #27170] ERROR -- Kitchen: ----End Backtrace-----
```

It could however be that I am totally overlooking something obvious here :D

**Comment by ncs-alane** [comment] 2018-09-14 15:58
Hi @encron.

Thank you for your interest in the project! I apologize for the inconvenience.

Terraform outputs are definitely still being exposed as InSpec attributes. It's hard to determine what this particular problem is caused by without more context. Are you able to share a repository which reproduces this issue?

**Comment by ncs-alane** [comment] 2018-09-14 21:28
@encron On further inspection, it appears that InSpec may have introduced a breaking change in how attributes are loaded. I will investigate. :grin:

**Comment by ncs-alane** [comment] 2018-09-14 22:37
It appears that InSpec 2.2.101 enhanced the implementation of attributes. Attributes must now be declared in InSpec profile files before they can be accessed.

https://github.com/inspec/inspec/pull/3318

**Comment by ncs-alane** [comment] 2018-09-15 17:52
@encron I am going to close this issue in favour of #274 but the solution should be shipped today!

**Closed by ncs-alane** 2018-09-15 17:52 UTC
Labels: bug, continuous integration, ruby gem, verifier, web site
