### ISSUE TITLE
Inspec AWS tests are skipped due to not supported platform

### ISSUE THREAD

**Issue by llibicpep** [newcontext-oss/kitchen-terraform#232] opened 2018-05-02 16:44 UTC
Using inspec 2.0 (that has introduced native support for AWS and a few other cloud providers) together with kitchen-terraform v3.3.1, I am having something like this:

```
  ↺  canary_bucket: S3 Bucket
     ↺  Resource Aws_s3_bucket is not supported on platform debian/9.3.
```

My understanding is that in inspec 2.0 they introduced the new platform types such as 'aws', while kitchen-terraform tells to inspec that the platform is whatever I run kitchen locally in.

**Comment by ncs-alane** [comment] 2018-05-02 17:25
Hi @llibicpep! Thanks for your interest in the project!

At the moment, Kitchen-Terraform only supports the local backend and the SSH backend. We are aware of the frustration that is causing and hope to release Kitchen-Terraform v4 soon which will introduce support for all InSpec backends / platforms. In the mean time, you can use the [awspec gem](https://github.com/k1LoW/awspec) in your project to obtain behaviour similar to InSpec's AWS resources.

**Comment by ncs-alane** [comment] 2018-05-02 21:09
@llibicpep I should clarify that resources provided by awspec can be used with InSpec controls, not as a replacement for them. As our support for InSpec's AWS resources improves, you should be able to simply replace the awspec resources with the native InSpec variety.

**Comment by ncs-alane** [comment] 2018-05-02 21:10
Also, thank you for the kind words! :grinning:

**Comment by llibicpep** [comment] 2018-05-02 21:35
Oh, I did't realized that. Is there an example how the whole thing (terraform+kitchen+inspec+awspec) can be configured to work together? All I can find seems to be standalone awspec setups, without inspec.

**Comment by ncs-alane** [comment] 2018-05-03 16:35
@llibicpep the extensive tutorial will be updated later today to demonstrate the use of awspec!

https://github.com/newcontext-oss/kitchen-terraform/pull/235

**Comment by llibicpep** [comment] 2018-05-10 14:46
Hi @ncs-alane, thanks for the info that looks helpful. However I'm not sure why are you closing this ticket, as inspec 2.0 does not fixed yet. And I want to bring your attention to the fact awspec is not a replacement, as it doesn't cover gcp and azure at all. The target is still to have inspec 2.0 fixed.

**Comment by ncs-alane** [comment] 2018-05-10 17:43
@llibicpep my mistake; over eager triaging! :sweat_smile:

**Comment by TheDigitalNinja** [comment] 2018-06-29 13:57
awspec 1.5 seems to requires aws-sdk 3 but kitchen-terraform requires aws-sdk 2. 

https://github.com/newcontext-oss/kitchen-terraform/blob/master/examples/extensive_kitchen_terraform/Gemfile

**Comment by ncs-alane** [comment] 2018-08-16 17:39
This should be fixed with #247 .

**Closed by ncs-alane** 2018-08-16 17:39 UTC

**Comment by ncs-alane** [comment] 2018-08-22 21:34
@TheDigitalNinja you need to use `backend: aws` to access InSpec's AWS resources.

**Comment by TheDigitalNinja** [comment] 2018-08-22 21:50
@ncs-alane Worked like a charm! This is now a game changer for how we build our modules in house. Great work on the 4.0.0 update.

**Comment by DavidJeche** [comment] 2018-08-22 22:10
@ncs-alane 

Well this got me much further than I was previously. I am deffo loving the concepts around it. I keep running in to the following issue's though. I am not sure if I should file a new issue report. The following error is what I am getting when trying to test ec2 instances.

> Profile: Extensive Kitchen-Terraform (extensive_suite)
> Version: 0.1.0
> Target:  aws://ec2-ec2-*-1*-6*-1*.eu-west-1.compute.amazonaws.com
> 
>   ×  reachable_other_host: Host  (3 failed)
>      ×  Host
>      Resource Host is not supported on platform aws/aws-sdk-v2.11.113.
>      ×  EC2 Instance i-0f53067cedae0b5d9 should exist
>      Encountered a `SocketError` while attempting to connect to:
> 
>        https://ec2.ec2-*-1*-6*-1*.eu-west-1.compute.amazonaws.com.amazonaws.com
> 
>      This is typically the result of an invalid `:region` option or a
>      poorly formatted `:endpoint` option.
> 
>      * Avoid configuring the `:endpoint` option directly. Endpoints are constructed
>        from the `:region`. The `:endpoint` option is reserved for connecting to
>        non-standard test endpoints.
> 
>      * Not every service is available in every region.
> 
>      * Never suffix region names with availability zones.
>        Use "us-east-1", not "us-east-1a"
> 
>      Known AWS regions include (not specific to this service):
> 
>      ap-northeast-1
>      ap-northeast-2

I think somewhere in the code there is an issue around passing arguments. I believe ec2 is meant to be appended else where. When I perform an nslookup on ec2-ec2-*-1*-6*-1*.eu-west-1.compute.amazonaws.com all is well. The ip is return but the alternative there is nothing. 

I do not know if that is just a display thing or if that is what is looked by the module.

I will try take a peek in the code sometime tomorrow.

**Comment by ncs-alane** [comment] 2018-08-22 23:12
Hi @DavidJeche.

Please open a new issue for your problem.

**Comment by DavidJeche** [comment] 2018-08-23 08:43
Ok I have tried it again now after taking and I can confirm that the issue I experienced was not a bug rather I miss configured the kitchen.yml file.

**Comment by BensamV** [comment] 2018-09-30 15:16
Kitchen Terraform Example for testing aws resources
https://github.com/BensamV/kitchen-terraform-aws
