### ISSUE TITLE
Unable to load Terraform driver

### ISSUE THREAD

**Issue by rubans** [newcontext-oss/kitchen-terraform#464] opened 2021-09-21 12:14 UTC
Folllowing the setup guide on mac:
https://newcontext-oss.github.io/kitchen-terraform/getting_started.html

However get the following error when running bundle exec kitchen converge:
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'terraform' driver. Error: undefined method `size' for nil:NilClass
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration

Running TF v1.0.7, ruby 2.6.8 and kitchen-terraform 6.0
Any ideas?

**Comment by aaron-lane** [comment] 2021-09-21 14:45
Hi @rubans! Thank you for your interest in the project.

Can you please provide the complete output of `bundle exec kitchen converge -l debug`?

**Comment by rubans** [comment] 2021-09-21 15:04
HI @aaron-lane
Thanks for your quick response.
Here's the log:
-----> Starting Test Kitchen (v2.12.0)
D      ------Exception-------
D      Class: Kitchen::ClientError
D      Message: Could not load the 'terraform' driver. Error: undefined method `size' for nil:NilClass
D      ----------------------
D      ------Backtrace-------
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/plugin.rb:45:in `rescue in load'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/plugin.rb:33:in `load'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/driver.rb:37:in `for_plugin'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:235:in `new_driver'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:250:in `new_instance'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:143:in `block in build_instances'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:142:in `map'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:142:in `with_index'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:142:in `build_instances'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:116:in `instances'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/command.rb:109:in `filtered_instances'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/command.rb:139:in `parse_subcommand'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/command/action.rb:34:in `block in call'
D      /usr/local/Cellar/ruby@2.6/2.6.8/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/command/action.rb:33:in `call'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/cli.rb:52:in `perform'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
D      /usr/local/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
D      /usr/local/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
D      /usr/local/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
D      /usr/local/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/bin/kitchen:11:in `block in <top (required)>'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/errors.rb:170:in `with_friendly_errors'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/bin/kitchen:11:in `<top (required)>'
D      /usr/local/lib/ruby/gems/2.6.0/bin/kitchen:23:in `load'
D      /usr/local/lib/ruby/gems/2.6.0/bin/kitchen:23:in `<top (required)>'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/cli/exec.rb:58:in `load'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/cli/exec.rb:58:in `kernel_load'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/cli/exec.rb:23:in `run'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/cli.rb:477:in `exec'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/cli.rb:31:in `dispatch'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/cli.rb:25:in `start'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/exe/bundle:49:in `block in <top (required)>'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/exe/bundle:37:in `<top (required)>'
D      /usr/local/opt/ruby@2.6/bin/bundle:23:in `load'
D      /usr/local/opt/ruby@2.6/bin/bundle:23:in `<main>'
D      ----End Backtrace-----
D      ---Nested Exception---
D      Class: NoMethodError
D      Message: undefined method `size' for nil:NilClass
D      ----------------------
D      ------Backtrace-------
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/plugin.rb:45:in `rescue in load'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/plugin.rb:33:in `load'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/driver.rb:37:in `for_plugin'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:235:in `new_driver'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:250:in `new_instance'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:143:in `block in build_instances'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:142:in `map'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:142:in `with_index'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:142:in `build_instances'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/config.rb:116:in `instances'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/command.rb:109:in `filtered_instances'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/command.rb:139:in `parse_subcommand'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/command/action.rb:34:in `block in call'
D      /usr/local/Cellar/ruby@2.6/2.6.8/lib/ruby/2.6.0/benchmark.rb:293:in `measure'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/command/action.rb:33:in `call'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/cli.rb:52:in `perform'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/cli.rb:198:in `block (2 levels) in <class:CLI>'
D      /usr/local/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/command.rb:27:in `run'
D      /usr/local/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/invocation.rb:127:in `invoke_command'
D      /usr/local/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor.rb:392:in `dispatch'
D      /usr/local/lib/ruby/gems/2.6.0/gems/thor-1.1.0/lib/thor/base.rb:485:in `start'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/bin/kitchen:11:in `block in <top (required)>'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/lib/kitchen/errors.rb:170:in `with_friendly_errors'
D      /usr/local/lib/ruby/gems/2.6.0/gems/test-kitchen-2.12.0/bin/kitchen:11:in `<top (required)>'
D      /usr/local/lib/ruby/gems/2.6.0/bin/kitchen:23:in `load'
D      /usr/local/lib/ruby/gems/2.6.0/bin/kitchen:23:in `<top (required)>'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/cli/exec.rb:58:in `load'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/cli/exec.rb:58:in `kernel_load'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/cli/exec.rb:23:in `run'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/cli.rb:477:in `exec'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/vendor/thor/lib/thor/command.rb:27:in `run'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/vendor/thor/lib/thor.rb:392:in `dispatch'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/cli.rb:31:in `dispatch'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/vendor/thor/lib/thor/base.rb:485:in `start'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/cli.rb:25:in `start'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/exe/bundle:49:in `block in <top (required)>'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/lib/bundler/friendly_errors.rb:128:in `with_friendly_errors'
D      /usr/local/lib/ruby/gems/2.6.0/gems/bundler-2.2.27/exe/bundle:37:in `<top (required)>'
D      /usr/local/opt/ruby@2.6/bin/bundle:23:in `load'
D      /usr/local/opt/ruby@2.6/bin/bundle:23:in `<main>'
D      ----End Backtrace-----

**Comment by aaron-lane** [comment] 2021-09-21 20:48
It is not immediately clear where `#size` is being called that is causing this issue. There are no instances of `#size` in this codebase, and none of the uses in `test-kitchen` immediately jump out as suspicious. Unfortunately the error handling within this part of `test-kitchen` obfuscates the true source of the error.

Can you please share your `kitchen.yml` for inspection?

**Comment by aaron-lane** [comment] 2021-09-21 20:55
Just FYI, I was also unable to reproduce this issue with:

- Ruby 2.6.8
- Kitchen-Terraform 6.0.0
- Terraform 1.0.6

This makes me think the issue may exist within your `kitchen.yml`.

**Comment by rubans** [comment] 2021-09-22 08:07
Hi @aaron-lane 
It's as simple as it can be (as per getting started wiki)
.kitchen.yml:
```
---
driver:
  name: terraform
  root_module_directory: test/fixtures/tf_module
  parallelism: 4

provisioner:
  name: terraform

verifier:
  name: terraform
  systems:
    - name: basic
      backend: local
      controls:
        - file_check

platforms:
  - name: terraform

suites:
  - name: kt_suite
```

**Comment by rubans** [comment] 2021-09-23 07:20
I don't think the issues is related to .kitchen.yml since it's same as what you have on the getting started wiki and is very simple.

**Comment by aaron-lane** [comment] 2021-09-23 14:36
@rubans sorry for the delay. Do you have a repository with the configuration that I could use to reproduce the issue?

**Comment by tbugfinder** [comment] 2021-12-30 21:16
close it?

**Closed** 2022-01-04 16:09 UTC
Labels: question
