### ISSUE TITLE
junit(2) is not a valid reporter type

### ISSUE THREAD

**Issue by wyardley** [newcontext-oss/kitchen-terraform#435] opened 2021-02-05 21:16 UTC
kitchen-terraform 5.6.0
kitchen-inspec 2.3.0
inspec(-bin) 4.26.0

I'm still having issues similar to https://github.com/inspec/inspec/issues/5243
It seems like this may now be an issue with kitchen-terraform itself (see https://github.com/inspec/kitchen-inspec/issues/272)

Let me know if I should be using the `inspec` verifier directly now, or if there's some other way to pass additional arguments to `inspec` when using this one.

# Steps to Reproduce:
`bundle exec kitchen verify`
my config currently looks like this:
```yaml
provisioner:
  name: "terraform"

platforms:
  - name: local

verifier:
  name: terraform
  systems:
    - name: remote-gcp
      backend: gcp
      reporter:
        - progress
        - json:/tmp/remote_gcp_inspec.json
        - junit2:/tmp/remote_gcp_inspec.xml
      controls:
        - foo
        - bar
    - name: local-outputs
      backend: local
      reporter:
        - progress
        - json:/tmp/local_inspec.json
      controls:
        - foo
        - bar
```

# Expected Result:
a junit report is created

# Actual Result:
```
>>>>>> Class: Kitchen::ActionFailed
>>>>>> Message: 1 actions failed.
>>>>>>     Failed to complete #verify action: ['junit' is not a valid reporter type.] on default-local
```

Same error whether I specify `junit` or `junit2`.
Note: json reporter does seem to work as expected here.

**Comment by aaron-lane** [comment] 2021-02-05 21:48
Ahoy @wyardley! Based on https://github.com/inspec/kitchen-inspec/issues/272#issuecomment-774289144, it looks like we may need to adjust how InSpec is being invoked by the Kitchen-Terraform verifier. 

I will note that it is certainly possible to use Kitchen-InSpec as the verifier, but you will lose out on the direct integration with Terraform provided by the Kitchen-Terraform verifier.

**Comment by wyardley** [comment] 2021-02-05 21:50
> I will note that it is certainly possible to use Kitchen-InSpec as the verifier, but you will lose out on the direct integration with Terraform provided by the Kitchen-Terraform verifier.

Yes -- overall, this has been working for me great as-is, so the plan is to leave things the same as long as I'm not doing something wrong!
So far, it hasn't been urgent to get junit reports working, but it's for sure a "nice to have".

Thanks for the quick response!

**Comment by tbugfinder** [comment] 2021-02-21 21:18
That's a duplicate of #426 :-)

**Comment by wyardley** [comment] 2021-02-21 21:30
Following #426. Thanks

**Closed** 2021-02-21 21:30 UTC
Labels: bug, ruby gem

**Comment by tbugfinder** [comment] 2021-02-24 22:03
Hi @wyardley ,
does 5.7.0 work for you?

**Comment by wyardley** [comment] 2021-02-24 22:25
@tbugfinder yeah, I was just testing with 5.7.0, but still seeing 
```
>>>>>>     Failed to complete #verify action: ['junit2' is not a valid reporter type.] on default-local
```
or
```
>>>>>>     Failed to complete #verify action: ['junit' is not a valid reporter type.] on default-local
```

**Comment by tbugfinder** [comment] 2021-02-25 18:53
Luckily, 5.7.1 works for me now.

**Comment by wyardley** [comment] 2021-02-25 20:34
@tbugfinder @aaron-lane can confirm that this works as expected with 5.7.1. Thanks all! 🎉
