### ISSUE TITLE
aws.provider no suitable version installed after `kitchen converge` 

### ISSUE THREAD

**Issue by mordant23** [newcontext-oss/kitchen-terraform#177] opened 2017-12-27 19:24 UTC
I followed the Advanced AWS example.

## Environment
kitchen-terraform version: 3.0.0
Terraform version: 0.11.1 (I've tried 0.10.2 as originally stated in the tutorial)
Ruby version: 2.4.3

Command: `bundle exec kitchen converge`

This seems related to https://github.com/hashicorp/terraform/issues/15757

## Expected Output
Tests could run

## Actual Output
```bash
$ bundle exec kitchen converge
-----> Starting Kitchen (v1.16.0)
$$$$$$ Running command `terraform version`
       Terraform v0.11.1
       
$$$$$$ Terraform v0.11.1 is supported
-----> Converging <example-ubuntu>...
$$$$$$ Running command `terraform workspace select kitchen-terraform-example-ubuntu`
$$$$$$ Running command `terraform get -update /home/mordant23/projects/terraform-testing-experiment/modules/amazon_advance_provider_example/test/fixtures/us_east_1`
       - module.example
         Updating source "../../../"
$$$$$$ Running command `terraform validate -check-variables=true    /home/mordant23/projects/terraform-testing-experiment/modules/amazon_advance_provider_example/test/fixtures/us_east_1`
       
       Error: 1 error(s) occurred:
       
       * provider.aws: no suitable version installed
         version requirements: "~> 0.1"
         versions installed: none
```

**Comment by ncs-alane** [comment] 2017-12-27 21:53
Hi @mordant23:

Thank you for your interest in the project!

If `terraform init` was not executed then it is likely that `kitchen create` was not executed. As the Test Kitchen commands are cumulative, `kitchen converge` should execute `kitchen create` unless the Test Kitchen instance is recorded as already being "created". Can you try running `bundle exec kitchen destroy` followed by `bundle exec kitchen converge`?

**Comment by mordant23** [comment] 2017-12-27 22:12
I see `terraform init` after I ran `bundle exec kitchen destroy`. When I run `bundle exec kitchen converge` afterwards, I get a different  error about an unset variable. Looks like the `bundle exec kitchen destroy` reset the kitchen instance.

**Comment by ncs-alane** [comment] 2017-12-28 13:55
`kitchen create` and `kitchen destroy` both execute `terraform init` because both commands must be able to execute successfully against an uninitialized Terraform working directory.

Do you need assistance in resolving the unset variable error?

**Comment by jpresley23** [comment] 2017-12-28 19:29
I'm no longer blocked. Is the expected workflow to run `bundle exec kitchen create` before running `bundle exec kitchen converge` the first time? I'm not sure if the root cause is documentation or a bug.

**Comment by jpresley23** [comment] 2017-12-28 19:33
I was able to figure out the unset variable error. I'd have to check my notes for the fix. It was a combination of user error and, I believe, a mismatch between the public key variable name in .kitchen.local.yml and the module in fixtures. Thank you for maintaining the tool.

**Comment by mordant23** [comment] 2017-12-28 19:44
Btw, the above comments were from my professional account. I didn't realize I was signed in under that account on my phone.

**Comment by ncs-alane** [comment] 2017-12-28 21:02
Executing `bundle exec kitchen converge` against a clean Test Kitchen state should result in `kitchen create` being automatically executed by Test Kitchen. If the Test Kitchen state is already considered to be "created" then `bundle exec kitchen converge` will not execute `kitchen create` again, which means that `terraform init` will not be executed.

Can you please share the possible mismatch in the example documentation so that we can try to solve the issue?

**Comment by mordant23** [comment] 2017-12-28 21:40
The variable is supposed to be `public_key_material`. In the tutorial it's `key_pair_public_key`.  There were a few other issues. You can see all of my notes https://github.com/mordant23/terraform-kitchen-experiments. One thing I didn't put down was the `fixtures` directory on the advanced AWS tutorial wasn't in `test`. If I weren't on vacation, I would've been happy to put in a PR for the documentation update. I really like this project.

**Comment by ncs-alane** [comment] 2017-12-31 02:45
@mordant23 thank you. I'll split those up in to issues.

**Comment by ncs-alane** [comment] 2018-01-09 22:50
Issues filed!
#191 
#192 
#193 
#194

**Closed by ncs-alane** 2018-01-09 22:50 UTC
Labels: question
