### ISSUE TITLE
kitchen-terraform destroy empty tf workspace - error

### ISSUE THREAD

**Issue by tbugfinder** [newcontext-oss/kitchen-terraform#289] opened 2018-11-22 21:16 UTC
Hello
from time to time I run into issues which I only can clear by removing .kitchen folder. Cleaning terraform temporary files does not fix it therefore I don't think it's related to terraform.

```
$$$$$$ Running command `terraform workspace select kitchen-terraform-default-test` in directory /home/myfolder/test/fixtures/default
       
       Workspace "kitchen-terraform-default-test" doesn't exist.
       
       You can create this workspace with the "new" subcommand.
$$$$$$ Running command `terraform workspace new kitchen-terraform-default-test` in directory /home/myfolder/test/fixtures/default
       Created and switched to workspace "kitchen-terraform-default-test"!
       
       You're now on a new, empty workspace. Workspaces isolate their state,
       so if you run "terraform plan" Terraform will not see any existing state
       for this configuration.
$$$$$$ Running command `terraform destroy -auto-approve -lock=true -lock-timeout=0s -input=false  -parallelism=10 -refresh=true  ` in directory /home/myfolder/test/fixtures/default
       data.aws_ami.test: Refreshing state...
       
       Error: Error applying plan:
       
       2 error(s) occurred:



$ bundle exec kitchen version
Test Kitchen version 1.23.2

```

**Comment by aaron-lane** [comment] 2018-11-23 20:50
Hi @tbugfinder!

Are you able to share the omitted error messages?

**Comment by ramgad** [comment] 2018-11-28 02:16
I've received the same error and wondering if any of you have recommendation on how to overcome this problem? Thank you!

**Comment by aaron-lane** [comment] 2018-11-28 16:02
@ramgad @tbugfinder if either of you are able to share your projects, or at least the Kitchen configuration files and complete output, that would be very helpful for triaging this issue.

**Comment by tbugfinder** [comment] 2018-11-29 15:55
Sorry for the delay.
Unfortunaltely I wasn't able to find the trigger when this error is really raised. After a cleanup of .kitchen folder I can execute it again.

We use a workspace within terrraform.
```
driver:
  name: terraform

provisioner:
  name: terraform

platforms:
- name: aws

verifier:
  name: terraform

suites:
- name: default
  driver:
    root_module_directory: test/fixtures/default
  verifier:
    systems:
    - name: aws
      backend: aws
      reporter:
      - cli
      - json:test/integration/default/myinspec.json
```

There's a .tf file which includes a lifecycle-keeper setting:
```
provider "random" {
  version = "2.0.0"
}

resource "random_string" "random_output" {
  keepers {
    lifecycle = "${terraform.workspace}"
  }

  length  = 20
  upper   = false
  lower   = true
  special = false
}

locals {
  ro = "${random_string.random_output.result}"
}
```

[kitchen.bugreport.log.txt](https://github.com/newcontext-oss/kitchen-terraform/files/2629842/kitchen.bugreport.log.txt)

**Comment by aaron-lane** [comment] 2018-11-29 20:09
@tbugfinder I believe lines 77-84 of kitchen.bugreport.log.txt indicate what the problem is.

> ---- Begin output of terraform destroy -auto-approve -lock=true -lock-timeout=0s -input=false  -parallelism=10 -refresh=true   ----
STDOUT: [0m[1mdata.aws_ami.rhel: Refreshing state...[0m
STDERR: [31m
[1m[31mError: [0m[0m[1mError applying plan:
>
> 1 error(s) occurred:
>
> * local.id: local.id: variable "id" is nil, but no error was reported

Does the Terraform configuration define a local `id` and a variable `id`?

**Comment by ramgad** [comment] 2018-11-30 07:11
Thank you for reaching out and I really appreciate it. I was able to
resolve the issue myself. Turns out that I had to remove the following line
from .kitchen.yml file

  reporter: doc

Additionally, I had incorrect pretty printing calls to see the values of
the attributes I had used in my ruby file.

Once I started seeing the errors that I could relate to and understand, I
was able to make progress and resolve all issues.

thank you again! hope this explains what I did to resolve the issue.

Ramesh

**Comment by tbugfinder** [comment] 2018-12-01 18:14
` TF_WARN_OUTPUT_ERRORS=1` is already included.

**Comment by aaron-lane** [comment] 2018-12-04 13:59
@tbugfinder removing the state file under `.kitchen` causes Kitchen to act like the instances have not been created. Can you please confirm the command that you are running and the point in the Kitchen workflow you are running the command?

**Comment by aaron-lane** [comment] 2018-12-04 13:59
Possible duplicate of #271

**Comment by tbugfinder** [comment] 2018-12-11 07:52
I'm executing:
TF_WARN_OUTPUT_ERRORS=1 bundle exec kitchen verify
bundle exec kitchen destroy

And yes, I'm running the same command after removing .kitchen.

**Comment by aaron-lane** [comment] 2018-12-11 14:33
@tbugfinder can you try prepending `TF_WARN_OUTPUT_ERRORS=1` to the `bundle exec kitchen destroy` command as well?

**Comment by aaron-lane** [comment] 2018-12-11 14:40
@tbugfinder are you able to share a repository which can reproduce this issue?

**Comment by tbugfinder** [comment] 2019-07-31 06:22
Still, this error is raised and always removing .kitchen helps us to overcome it.
Will try to build reproducible steps as there has to be some specific order - I think.

**Comment by tbugfinder** [comment] 2019-07-31 16:51
Finally I've managed to build something reproducible.
https://github.com/tbugfinder/kttf289

**Comment by tbugfinder** [comment] 2019-08-14 06:51
Maybe it's linked to https://github.com/test-kitchen/test-kitchen/issues/1436 

Usually I'm using `bundle exec kitchen verify` and `bundle exec kitchen destroy`.
Today I was using `bundle exec kitchen test` which indeed starts with the `destroy` phase failing directly with the error message raised here:
```

       Error: Error applying plan:

       1 error occurred:
        * local.id: local.id: Resource 'random_id.id' does not have attribute 'hex' for variable 'random_id.id.hex'


```

**Comment by aaron-lane** [comment] 2019-08-21 02:01
@tbugfinder all of the information in this thread still points to #271. The reproduction repository which you provided is demonstrating a different issue which I'll discuss below.

Uncommenting `#breakit` introduces a Terraform syntax error which causes `make -f Makefile.test test` (`test`) to fail, as is expected. At this point, the Kitchen instance was successfully created but unsucessfully converged:

```sh
$ bundle exec kitchen list
Instance     Driver     Provisioner  Verifier   Transport  Last Action  Last Error
default-aws  Terraform  Terraform    Terraform  Ssh        Created      Kitchen::ActionFailed
```

Commenting `#breakit` removes the Terraform syntax error and yet running `test` at this point still fails as you noted:

```sh
$$$$$$ Running command `terraform validate   ` in directory /home/aaron/src/kttf289/test/fixtures/default
       
       Error: 1 error occurred:
       	* provider.random: no suitable version installed
         version requirements: "(any version)"
         versions installed: none
```

The failure is unrelated to the content of this thread, though. `test` starts by removing `.terraform` and `terraform.tfstate.d` of the module under test. It then attempts to verify the Kitchen instance, and because the Kitchen instance is still considered to be created, Kitchen-Terraform expects the module to already be initialized and skips to applying the configuration, which fails due to the abscence of `provider.random` because the module was uninitialized when `.terraform` was removed. Because `test` also unconditionally destroys the Kitchen instance, running it again succeeds because the Kitchen instance is now created, which initializes the module.

[As I mentioned previously](https://github.com/newcontext-oss/kitchen-terraform/issues/289#issuecomment-444108879), removing `.kitchen` is simply tricking Kitchen in to starting from the beginning of the workflow because its state file is being removed.

**Closed** 2020-02-29 15:24 UTC
